train_dir = None
#train_annotation = '/workspace/mnt/cache/datasets/ocr_pub/icdar_icpr.json'
train_annotation = '/workspace/mnt/cache/datasets/waimai/train/train.json'
val_dir = None
#val_annotation = '/workspace/mnt/cache/datasets/ocr_test/ocr-test-1535/ocr-test-1535.json'
val_annotation = '/workspace/mnt/cache/datasets/waimai/val/waimai_val_set_00.json'
backbone = 'resnet18' # resnet50 or resnet18
batch_size = 12
lr = 1e-4 #scratch
#lr = 1e-6 #finetune
weight_decay = 1e-5
epochs = 50
warm_up = 20
num_workers = 4
input_size = 256
text_scale = 256
inference_size = (192, 256) # int or tuple(w, h), int时等比例缩放并限制长边尺寸<inference_size, tuple时, resize成inference_size
min_text_size = 10
gpus = "0" # gpu ids
backbone_pretrain = True
checkpoint_dir = './checkpoint_waimai'
checkpoint = None
finetune = False # finetune from checkpoint, reset optimizer if True else restore optimizer from checkpoint
print_freq = 2
eval_interval = 5 # eval interval (epoch)
tensorboardX = None
